version: "3.9"
volumes:
  dbdata:
  code:
services:
  webserver:
    container_name: webserver
    build:
      context: docker/apache
      dockerfile: Dockerfile
    environment:
      DB_ADDR: "${DB_ADDR}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "89:80"
    volumes:
      - /:/var/www/html

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
      - ./docker/mariadb:/docker-entrypoint-initdb.d
