version: "3.8"

services:
  webserver:
    container_name: webserver
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    environment:
      DB_ADDR: "${DB_ADDR}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - ":9000"
    volumes:
      - ./:/var/www/html
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - "/tmp/xdebug:/tmp/xdebug"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./docker/mariadb/:/docker-entrypoint-initdb.d
