<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'mvcex\\api\\lib\\dbconnector' => '/api/lib/database.php',
                'mvcex\\api\\lib\\routecontract' => '/api/lib/route.php',
                'mvcex\\core\\database' => '/core/database.php',
                'mvcex\\core\\query' => '/core/query.php',
                'mvcex\\core\\request' => '/core/request.php',
                'mvcex\\core\\response' => '/core/response.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
