<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'mvcex\\api\\lib\\apicontroller' => '/api/lib/APIController.php',
                'mvcex\\api\\lib\\apimodel' => '/api/lib/APIModel.php',
                'mvcex\\api\\lib\\apimodelcollection' => '/api/lib/APIModelCollection.php',
                'mvcex\\api\\lib\\apiresponse' => '/api/lib/APIResponse.php',
                'mvcex\\api\\lib\\command' => '/api/lib/Commands.php',
                'mvcex\\api\\lib\\dbconnector' => '/api/lib/DBConnector.php',
                'mvcex\\api\\lib\\exceptions\\apiexception' => '/api/lib/exceptions/ApiException.php',
                'mvcex\\api\\lib\\exceptions\\dbexception' => '/api/lib/exceptions/DBException.php',
                'mvcex\\api\\lib\\exceptions\\invalidcredentials' => '/api/lib/exceptions/InvalidCredentias.php',
                'mvcex\\api\\lib\\exceptions\\invalidinputs' => '/api/lib/exceptions/InvalidInputs.php',
                'mvcex\\api\\lib\\exceptions\\notfound' => '/api/lib/exceptions/NotFound.php',
                'mvcex\\api\\lib\\middleware\\common\\datavalidation' => '/api/lib/middleware/common/DataValidation.php',
                'mvcex\\api\\lib\\middleware\\middlewarehandler' => '/api/lib/middleware/MiddlewareHandler.php',
                'mvcex\\api\\lib\\middleware\\wareschain' => '/api/lib/middleware/WaresChain.php',
                'mvcex\\api\\lib\\middleware\\warescontext' => '/api/lib/middleware/WaresContext.php',
                'mvcex\\api\\lib\\validation\\filter' => '/api/lib/validation/Filter.php',
                'mvcex\\api\\lib\\validation\\isarray' => '/api/lib/validation/IsArray.php',
                'mvcex\\api\\lib\\validation\\required' => '/api/lib/validation/Required.php',
                'mvcex\\api\\lib\\validation\\validator' => '/api/lib/validation/Validator.php',
                'mvcex\\api\\routes\\logincontract' => '/api/routes/login/LoginContract.php',
                'mvcex\\api\\routes\\notecontract' => '/api/routes/note/NoteContract.php',
                'mvcex\\api\\routes\\notfoundcontract' => '/api/routes/errors/NotFoundContract.php',
                'mvcex\\api\\services\\auth\\authcontroller' => '/api/services/auth/AuthController.php',
                'mvcex\\api\\services\\auth\\loginmodel' => '/api/services/auth/LoginModel.php',
                'mvcex\\api\\services\\auth\\middleware\\loginhandler' => '/api/services/auth/middleware/LoginHandler.php',
                'mvcex\\api\\services\\notes\\notemodel' => '/api/services/notes/NoteModel.php',
                'mvcex\\api\\services\\notes\\notescollection' => '/api/services/notes/NotesCollection.php',
                'mvcex\\api\\services\\notes\\notescontroller' => '/api/services/notes/NotesController.php',
                'mvcex\\core\\database' => '/core/Database.php',
                'mvcex\\core\\model' => '/core/Model.php',
                'mvcex\\core\\response' => '/core/Response.php',
                'mvcex\\core\\routecontract' => '/core/RouteContract.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
